baseURL = 'https://2134765.vercel.app/'
languageCode = 'en-us'
title = "2134765"
description = "my thoughts"
theme = "PaperMod"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

[params]
  description = "notes"
  useTitle = true
  
[markup.goldmark.renderer]
unsafe = true
